### ISSUE TITLE
with gpg v2.1 GPG_AGENT_INFO is removed

### ISSUE THREAD

**Issue by Lompik** [tarsius/keychain-environment#4]
Just a heads up. 
https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart

This leads to `~/.keychain/*.gpg` files to be empty. 

https://github.com/funtoo/keychain/issues/59

Regards.

**Comment by tarsius** [comment]
Thanks for the heads up. Unfortunately we'll have to wait for the Funtoo people to do something about this. (Side note: I once was a Funtoo user, contributor even, but have since moved on to Debian ;-).

**Comment by tarsius** [comment]
To anyone affected by this; please help upstream with https://bugs.funtoo.org/browse/FL-3405.

I am closing this now and recommend that you use a workaround if you don't have the time to help upstream. https://github.com/funtoo/keychain/issues/59#issuecomment-279379086 looks reasonable, but maybe the other proposed approaches work better for you.
