### ISSUE TITLE
thx!! a auto start question?

### ISSUE THREAD

**Issue by zeltak** [tarsius/keychain-environment#5]
thx so much this is *exactly* what ive been looking for!

im using emacs on arch and emacs would not allow me to push to git, ssh etc from within emacs since i start it with systemd

im a complete neewb when it comes to coding so this question is probably trivial. how can i make emacs auto launch `keychain-refresh-environment` when i start emacs. so i need to specify that in my init?

currently the relevant section looks like this

```
(use-package keychain-environment
 :ensure t
 :config
  )
```
thx so much

Z

**Comment by tarsius** [comment]
That's what I use:

```lisp
(use-package keychain-environment
  :config (keychain-refresh-environment))
```
