### ISSUE TITLE
Not working when $SHELL is fish shell

### ISSUE THREAD

**Issue by ddoherty03** [tarsius/keychain-environment#6]
tarsius,

Just started using the fish shell, and liking it alot.  It has a different syntax for setting environment variables, and `keychain --eval` will output the fish syntax when $SHELL is set to the fish shell.

I get this from `keychain  --eval -Q --quiet id_rsa --nogui`

    set -e SSH_AUTH_SOCK; set -x -U SSH_AUTH_SOCK /tmp/ssh-X30j8bWvwPIQ/agent.4799;
    set -e SSH_AGENT_PID; set -x -U SSH_AGENT_PID 4976;

and similar for GPG_AGENT_INFO.  This, the regular-expression match does not properly capture the environment variable settings.

**Comment by tarsius** [comment]
I've updated the regexps to support `fish` and `csh`.

**Comment by ddoherty03** [comment]
@tarsius, many thanks for the fix.
